################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "0.0.0.0"
    # Port on which we bind (default: 3000)
    port: 3001

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # The name of the folder where the logs are stored.
    folder: logs
    # Values: error, warn, info, http, verbose, debug, silly
    level: debug
    # Default to false
    console: true

node:
  interval: 5
  max_txs: 8
  send_interval: 1
  ipfs_api_url: http://localhost:5001
  ipfs_gateway_url: http://localhost:8080
  ipfs_test: true

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      interval: 1
    - name: send_block
      enable: true
      interval: 1

database:
  path: ":memory:"

contracts:
  rollup_manager_key: "0x94bf5604b9eb7990985dfabbfd1298a16a3c94cb79a5fa39638279ba9ca48a80"
  rollup_address: "0x0000000000000000000000000000000000000000"

authorization:
  api_access_token: 9812176e565a007a84c5d2fc4cf842b12eb26dbc7568b4e40fc4f2418f2c8f54
