################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "0.0.0.0"
    # Port on which we bind (default: 3000)
    port: 3001

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # The name of the folder where the logs are stored.
    folder: logs
    # Values: error, warn, info, http, verbose, debug, silly
    level: http
    # Default to false
    console: true

node:
  interval: 5
  max_txs: 8
  ipfs_api_url: http://localhost:5001
  ipfs_gateway_url: http://localhost:8080
  ipfs_test: true

scheduler:
  enable: true
  items:
    - name: node
      enable: true
      interval: 1

