name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copy env
        if: runner.os != 'windows'
        run: cp env/.env.sample env/.env

      - name: Copy env
        if: runner.os == 'windows'
        run: copy env\.env.sample env\.env

      - name: npm install, build, and test
        run: |
          npm ci
          npx hardhat compile
          npx hardhat test
          echo 'everything is done'
        env:
          CI: true
